# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ea521d959b5067b580a5dcfe1c3b341fda8e2ea08e92fc9d6f0e1e013cef80ce85246643b1a1130ce2510ce0247cd93102da6a54af39afda81be46de8331ed

test:
  secret_key_base: e9d38893bcc48c89e346730bf2036e66c2907f4a7e75d45ef0c48b26608456fe8e043eb28ef6cb072011ba8023e31c5ac6b466f63ddcc1c471de1cac8717bc83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
