# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 837250fa8e08ac981de631c52ec7d957439ca914fe1b35afd7c34d90b4f1d1a5c2aafaf8148440aa427665257af232d8e0bb839a66e540606f1d31876b4637cc

test:
  secret_key_base: cb5d7da4883ff74cf4a5ac1fb0692ed3f7e1530bb75779a3c7dbd0f620f72b55d54e5d095ec018a48883eb75a6b174ebe7aa9ee63dfd600450c464164215c843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
